/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'calm' : IDL.Null,
  'grateful' : IDL.Null,
  'excited' : IDL.Null,
  'neutral' : IDL.Null,
});
export const EntryMode = IDL.Variant({
  'aiPrompted' : IDL.Null,
  'freeWrite' : IDL.Null,
});
export const Time = IDL.Int;
export const DiaryEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mode' : EntryMode,
  'mood' : Mood,
  'createdAt' : Time,
  'aiPrompt' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChatMessage = IDL.Record({
  'message' : IDL.Text,
  'fromUser' : IDL.Bool,
});
export const MoodCount = IDL.Record({ 'mood' : Mood, 'count' : IDL.Nat });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdminFirstCaller' : IDL.Func([], [IDL.Bool], []),
  'createEntry' : IDL.Func(
      [IDL.Text, IDL.Text, Mood, IDL.Opt(IDL.Text), EntryMode],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'endChatSession' : IDL.Func([], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], []),
  'getAllEntriesSortedByTitle' : IDL.Func([], [IDL.Vec(DiaryEntry)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getEntriesForCaller' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
  'getEntriesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DiaryEntry)],
      ['query'],
    ),
  'getPromptsForMood' : IDL.Func([Mood], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyMoodAnalysis' : IDL.Func([], [IDL.Vec(MoodCount)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessageToCompanion' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Mood], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'calm' : IDL.Null,
    'grateful' : IDL.Null,
    'excited' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const EntryMode = IDL.Variant({
    'aiPrompted' : IDL.Null,
    'freeWrite' : IDL.Null,
  });
  const Time = IDL.Int;
  const DiaryEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mode' : EntryMode,
    'mood' : Mood,
    'createdAt' : Time,
    'aiPrompt' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'message' : IDL.Text,
    'fromUser' : IDL.Bool,
  });
  const MoodCount = IDL.Record({ 'mood' : Mood, 'count' : IDL.Nat });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdminFirstCaller' : IDL.Func([], [IDL.Bool], []),
    'createEntry' : IDL.Func(
        [IDL.Text, IDL.Text, Mood, IDL.Opt(IDL.Text), EntryMode],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'endChatSession' : IDL.Func([], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], []),
    'getAllEntriesSortedByTitle' : IDL.Func([], [IDL.Vec(DiaryEntry)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getEntriesForCaller' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
    'getEntriesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DiaryEntry)],
        ['query'],
      ),
    'getPromptsForMood' : IDL.Func([Mood], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyMoodAnalysis' : IDL.Func([], [IDL.Vec(MoodCount)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessageToCompanion' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Mood], [], []),
  });
};

export const init = ({ IDL }) => { return []; };