/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage { 'message' : string, 'fromUser' : boolean }
export interface DiaryEntry {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'mode' : EntryMode,
  'mood' : Mood,
  'createdAt' : Time,
  'aiPrompt' : [] | [string],
}
export type EntryMode = { 'aiPrompted' : null } |
  { 'freeWrite' : null };
export type Mood = { 'sad' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'calm' : null } |
  { 'grateful' : null } |
  { 'excited' : null } |
  { 'neutral' : null };
export interface MoodCount { 'mood' : Mood, 'count' : bigint }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<
    [string, string, Mood, [] | [string], EntryMode],
    bigint
  >,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'endChatSession' : ActorMethod<[], undefined>,
  'getAllEntries' : ActorMethod<[], Array<DiaryEntry>>,
  'getAllEntriesSortedByTitle' : ActorMethod<[], Array<DiaryEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getEntriesForCaller' : ActorMethod<[], Array<DiaryEntry>>,
  'getEntriesForUser' : ActorMethod<[Principal], Array<DiaryEntry>>,
  'getPromptsForMood' : ActorMethod<[Mood], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyMoodAnalysis' : ActorMethod<[], Array<MoodCount>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessageToCompanion' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateEntry' : ActorMethod<[bigint, string, string, Mood], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];