/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DiaryEntry {
    id: bigint;
    title: string;
    body: string;
    mode: EntryMode;
    mood: Mood;
    createdAt: Time;
    aiPrompt?: string;
}
export interface MoodCount {
    mood: Mood;
    count: bigint;
}
export interface ChatMessage {
    message: string;
    fromUser: boolean;
}
export interface UserProfile {
    name: string;
    age?: number;
}
export interface http_header {
    value: string;
    name: string;
}
export enum EntryMode {
    aiPrompted = "aiPrompted",
    freeWrite = "freeWrite"
}
export enum Mood {
    sad = "sad",
    anxious = "anxious",
    happy = "happy",
    angry = "angry",
    calm = "calm",
    grateful = "grateful",
    excited = "excited",
    neutral = "neutral"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export type ApprovalStatus = { approved: null } | { pending: null } | { rejected: null };
export interface UserApprovalInfo { user: Principal; status: ApprovalStatus; }
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEntry(title: string, body: string, mood: Mood, aiPrompt: string | null, mode: EntryMode): Promise<bigint>;
    deleteEntry(entryId: bigint): Promise<void>;
    endChatSession(): Promise<void>;
    getAllEntries(): Promise<Array<DiaryEntry>>;
    getAllEntriesSortedByTitle(): Promise<Array<DiaryEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getEntriesForCaller(): Promise<Array<DiaryEntry>>;
    getEntriesForUser(user: Principal): Promise<Array<DiaryEntry>>;
    getPromptsForMood(mood: Mood): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyMoodAnalysis(): Promise<Array<MoodCount>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessageToCompanion(message: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateEntry(entryId: bigint, newTitle: string, newBody: string, newMood: Mood): Promise<void>;
}
import type { DiaryEntry as _DiaryEntry, EntryMode as _EntryMode, Mood as _Mood, MoodCount as _MoodCount, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEntry(arg0: string, arg1: string, arg2: Mood, arg3: string | null, arg4: EntryMode): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEntry(arg0, arg1, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_EntryMode_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEntry(arg0, arg1, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_EntryMode_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async endChatSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endChatSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endChatSession();
            return result;
        }
    }
    async getAllEntries(): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEntriesSortedByTitle(): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntriesSortedByTitle();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntriesSortedByTitle();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getEntriesForCaller(): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesForCaller();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesForCaller();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesForUser(arg0: Principal): Promise<Array<DiaryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesForUser(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesForUser(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromptsForMood(arg0: Mood): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptsForMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptsForMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyMoodAnalysis(): Promise<Array<MoodCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyMoodAnalysis();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyMoodAnalysis();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        const result = await this.actor.isCallerApproved();
        return result;
    }
    async requestApproval(): Promise<void> {
        await this.actor.requestApproval();
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        const result = await this.actor.listApprovals();
        return result as Array<UserApprovalInfo>;
    }
    async setApproval(user: Principal, status: ApprovalStatus): Promise<void> {
        await this.actor.setApproval(user, status);
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        const candid = { name: arg0.name, age: arg0.age != null ? [BigInt(arg0.age)] as [bigint] : [] as [] };
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(candid);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(candid);
            return result;
        }
    }
    async sendMessageToCompanion(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToCompanion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToCompanion(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateEntry(arg0: bigint, arg1: string, arg2: string, arg3: Mood): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEntry(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEntry(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_DiaryEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiaryEntry): DiaryEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_EntryMode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntryMode): EntryMode {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_MoodCount_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodCount): MoodCount {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    if (value.length === 0) return null;
    const v = value[0];
    return { name: v.name, age: v.age && v.age.length > 0 ? Number(v.age[0]) : undefined };
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    mode: _EntryMode;
    mood: _Mood;
    createdAt: _Time;
    aiPrompt: [] | [string];
}): {
    id: bigint;
    title: string;
    body: string;
    mode: EntryMode;
    mood: Mood;
    createdAt: Time;
    aiPrompt?: string;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        mode: from_candid_EntryMode_n11(_uploadFile, _downloadFile, value.mode),
        mood: from_candid_Mood_n13(_uploadFile, _downloadFile, value.mood),
        createdAt: value.createdAt,
        aiPrompt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.aiPrompt))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: _Mood;
    count: bigint;
}): {
    mood: Mood;
    count: bigint;
} {
    return {
        mood: from_candid_Mood_n13(_uploadFile, _downloadFile, value.mood),
        count: value.count
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiPrompted: null;
} | {
    freeWrite: null;
}): EntryMode {
    return "aiPrompted" in value ? EntryMode.aiPrompted : "freeWrite" in value ? EntryMode.freeWrite : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    calm: null;
} | {
    grateful: null;
} | {
    excited: null;
} | {
    neutral: null;
}): Mood {
    return "sad" in value ? Mood.sad : "anxious" in value ? Mood.anxious : "happy" in value ? Mood.happy : "angry" in value ? Mood.angry : "calm" in value ? Mood.calm : "grateful" in value ? Mood.grateful : "excited" in value ? Mood.excited : "neutral" in value ? Mood.neutral : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodCount>): Array<MoodCount> {
    return value.map((x)=>from_candid_MoodCount_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiaryEntry>): Array<DiaryEntry> {
    return value.map((x)=>from_candid_DiaryEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EntryMode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntryMode): _EntryMode {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    calm: null;
} | {
    grateful: null;
} | {
    excited: null;
} | {
    neutral: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.anxious ? {
        anxious: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.angry ? {
        angry: null
    } : value == Mood.calm ? {
        calm: null
    } : value == Mood.grateful ? {
        grateful: null
    } : value == Mood.excited ? {
        excited: null
    } : value == Mood.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntryMode): {
    aiPrompted: null;
} | {
    freeWrite: null;
} {
    return value == EntryMode.aiPrompted ? {
        aiPrompted: null
    } : value == EntryMode.freeWrite ? {
        freeWrite: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
